### ISSUE TITLE
UC Gestione CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#10]

**Comment by Matteosalvatori4** [comment]
Creato e implementato lato server. Con commit f31ddfed1ed500d2a56e1ceb08f09ae567283869

**Comment by lollo996** [comment]
implementato lato client  gestione-CD. con commit. 5defc2039b2fee2b0fef2c6e25a64d1aa992dea1

**Comment by Fmarro** [comment]
verificate funzionalità lato client e lato server
