### ISSUE TITLE
UC Mostra Tutti i Conti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#11]

**Comment by Valerio1990** [comment]
23001fd3f4450c61b277b1b337924b184d8a1ffe

**Comment by Valerio1990** [comment]
5ec87829e4355fa68987b57f0c719f76e7cd6dd8
Implementato metodo cerca lato client

**Comment by Valerio1990** [comment]
1e7825b7e145e37f2f2b34693611c10a7ac822c9

**Comment by Valerio1990** [comment]
47171624245b6340a8ddfe8519d12ba1d4f4041e
