### ISSUE TITLE
Server: associazione tra ContoDeposito e Cliente

### ISSUE THREAD

**Issue by mainieritm** [luca-lezzerini/conto-banca-j#13]
E' una relazione Molti a Molti o Uno a Molti?
Non riusciamo a capire come definire la tabella ClienteCD.

**Comment by luca-lezzerini** [comment]
E' una uno a molti, ignorate la classe di associazione ClienteCD
Quindi chiudete questo ticket

**Comment by mainieritm** [comment]
Grazie
