### ISSUE TITLE
Client: richiesta approvazione modifica app-routing.module #8

### ISSUE THREAD

**Issue by Matteosalvatori4** [luca-lezzerini/conto-banca-j#18]
Client: richiesta approvazione modifica app-routing.module #8

**Comment by Fmarro** [comment]
approvata, appena finite di lavorare con l'app-routing.module vi prego di pushare subito e chiudere il ticket

**Comment by Fmarro** [comment]
chiuso con commit: d35b9f069e81eec1ba33c0e36b67074223b110ee
