### ISSUE TITLE
Interfaccia utente: campo Data di nascita

### ISSUE THREAD

**Issue by mainieritm** [luca-lezzerini/conto-banca-j#22]
![Entità Cliente](https://user-images.githubusercontent.com/79866026/111904642-336d1f80-8a48-11eb-9320-d71ead729aca.PNG)
![Interfaccia gest-utente](https://user-images.githubusercontent.com/79866026/111904643-3405b600-8a48-11eb-90e9-f3b04e754a36.PNG)

Prof, 
ci chiedevamo se dovessimo aggiungere la data di nascita nell'interfaccia utente, visto che nell'entità c'è, ma non compare nell'interfaccia.
Allego screenshot documentazione.

**Comment by luca-lezzerini** [comment]
No, non è necessario
