### ISSUE TITLE
Associa CC

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#29]

**Comment by g-golia** [comment]
Commit: 09770aea50a650612265437c111f6b98ac9cc7c0

**Comment by g-golia** [comment]
Risoluzione parziale: 8dcf61deaace90134e403bffae3e377d37c30f1f

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale Commit: 63003c742296436c8caee21c06d20470106de7fa

**Comment by AulicinoDiego** [comment]
chiuso con commit : f812cd87eb5cad03ef5780c9aed05ef2403862e7
