### ISSUE TITLE
Associa CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#31]

**Comment by Fmarro** [comment]
creato service, serviceImpl e controller lato server con commit: 5e03c8c81675d188210d3a3d4186bcddeeb6b71b

**Comment by Matteosalvatori4** [comment]
Implementato lato client con commit bb1bd5d2e920c87dfb6531c05af4dd027319d128

**Comment by Fmarro** [comment]
completati ultimi metodi e test con commit: d5454d2a818943d0380fbaa8e9d4ba36a748180c

**Comment by Matteosalvatori4** [comment]
Risolto problema ricerca conto. commit finale 587590747869cdfca93f169864c639737f90a3d1
