### ISSUE TITLE
Saldo CC

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#35]

**Comment by g-golia** [comment]
Commit: eb7b087b4c910a800ebc6481d9a067d4c8bb6da4

**Comment by AulicinoDiego** [comment]
commit : 7051594ccf647e594179bdd97747b7b55bc77df3

**Comment by RobertaConti-Jarvis** [comment]
risolto ticket con commit: b7d917f41b3ef08ed73ad086ad2e3422df3525fe
