### ISSUE TITLE
Creare CSS

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#4]
Creare un foglio di stile CSS globale nel client (dentro app) chiamato theme.css.
Definire a piacere gli stili per:

titolo-grande
etichetta-testo
etichetta-bottone
bottone-attivo
bottone-disabilitato
campo-input
body
tabella
header-tabella
riga-tabella

**Comment by danieleSantini** [comment]
b17f8910406cf1c63cd965d713b621fc1fbb0f34
