### ISSUE TITLE
Movimenti CD

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#49]

**Comment by Fmarro** [comment]
creato ed implementata logica lato server. creato component lato client e modificato l'app-module.ts con commit: d0b7446f8aaf3d2d121fcc16af66129132b27342

**Comment by Fmarro** [comment]
implementata logica con commit: aadde91378d5fdeae1c7db3f55aa182440f35426

**Comment by Ioana21-b** [comment]
Chiuso con commit 3cd58a9622dfaa0f4b443dca8ec68dbc357dbbd0

**Comment by Fmarro** [comment]
risolti bug lato client con commit: 0ce5e861c4505ef3226ce24a7afc69dc0f7a99a9
