### ISSUE TITLE
Paginazione della gestione clienti

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#51]
Multiscelta 10,25, 50 elementi per pagina con combobox.
Comandi di navigazione:
prima pagina (<<)
Pagina precedente (<)
Una pagina prima
Pagina corrente (input per cambiare al volo il numero di pagina)
Ultima pagina
Pagina successiva (>)
Ultima pagina (>>)

**Comment by g-golia** [comment]
Commit: c9d183f64b89a4e2f8d258ae095e32a86a374148

**Comment by RobertaConti-Jarvis** [comment]
Commit: 6468e9ab4b31102337a79c0fdb1abb9fbc75c4b2

**Comment by AulicinoDiego** [comment]
Commit : 6c153b1e5b8ba4935ba391126cce773e8fa3a157

**Comment by AulicinoDiego** [comment]
commit : 320d0b44dd1c1d3a4c77ba17c7a577b43d8af61d
