### ISSUE TITLE
richiesta creazione componenti Movimenta CD e modifica app-routing-module

### ISSUE THREAD

**Issue by lollo996** [luca-lezzerini/conto-banca-j#54]
richiesta creazione componenti Movimenta CD e modifica app-routing-module

**Comment by Fmarro** [comment]
approvata, per favore pushare appena finita la creazione e le modifiche

**Comment by Fmarro** [comment]
risolto con commit: d0b7446f8aaf3d2d121fcc16af66129132b27342
