### ISSUE TITLE
Creare Generatore dati test

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#6]
Risponde a richiesta genera-dati-test.

Creare un controller che riceve la richiesta, void e senza parametri (potete chiamarlo da URL o con semplice GET).
Il conrtroller chiama il metodo generaDatiTest del servizio SystemAdminService che crea e associa i vari dati di test.
Prima dic reare i dati di test, il servizio cancella tutte le tabelle

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale con Commit: 40b12cd5c917c777b4cf864c566a27fd76c5ddbe

**Comment by irenedg** [comment]
Risoluzione parziale con Commit: ef72850bb279c3db17b9e5ae1420406b3f0429e8

**Comment by AulicinoDiego** [comment]
Risoluzione parziale con Commit: b229e75e918f66325fbc1c7129b3d6f9bbc25339

**Comment by RobertaConti-Jarvis** [comment]
Risoluzione parziale con Commit: 4bc3e6295712a5cc88889ae2015dcc6cc01f2fee

**Comment by irenedg** [comment]
Risolto ticket con Commit: f9d566f9efb6b88a05a3d53fdfd314277d438037
