### ISSUE TITLE
UC Gestione CC

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/conto-banca-j#8]

**Comment by Matteosalvatori4** [comment]
Implementato lato server con commit 0df03614785b77acdafeaa33334ae1870c916145.
Da Implementare meteodo aggiungi().

**Comment by SamueleM21** [comment]
implementato metodo new lato client con commit: 16b52124a5e2c6f6b76a8659f1d9c1fdb2da0d67

**Comment by Matteosalvatori4** [comment]
Implementato metodo elimina con commit efe5bafc03d142a591a7eb81c805e8e9404a2796

**Comment by SamueleM21** [comment]
implementato metodo elimina() lato client con commit : 926e2d00e7fa4d06e14fdc4e1ce601410d6bcd08

**Comment by Fmarro** [comment]
implementato e verificato funzionalità di tutti i servizi sia lato client che lato server con commit: b92c07ba4268a8707e8b24a6f0171871d8bfa3a7

**Comment by Fmarro** [comment]
completate ultime implementazioni e verificate le varie funzionalità con commit: 5450effc6650d1f763004ee239395518862ffbaf
